
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async saveApiKey(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_api_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadApiKey() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteApiKey() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveImagesBatch(images: ImageRecord[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_images_batch", { images }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchSimilarImages(path: string) : Promise<Result<SimilarImageHit[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_similar_images", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getImagePalette(id: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_image_palette", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async backfillVisualSignatures(limit: number) : Promise<Result<VisualBackfillResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backfill_visual_signatures", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reconcileInvokeOwnerInventory(input: InvokeImageOwnerInventoryInput) : Promise<Result<InvokeImageSourceReconcileResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reconcile_invoke_owner_inventory", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reconcileInvokeImageSources(updates: InvokeImageSourceUpdate[]) : Promise<Result<InvokeImageSourceReconcileResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reconcile_invoke_image_sources", { updates }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async replaceInvokeImageReferences(referenceSets: InvokeImageReferenceSet[]) : Promise<Result<InvokeImageReferenceReplaceResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("replace_invoke_image_references", { referenceSets }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveImagePathIdentities(moves: ImagePathIdentityMove[]) : Promise<Result<ImagePathIdentityMoveResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_image_path_identities", { moves }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markImagePathIdentitiesMissing(ids: string[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_image_path_identities_missing", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMainDatabaseUrl() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_main_database_url") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDbDiagnostics() : Promise<Result<DbDiagnostics, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_db_diagnostics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showAppLogFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_app_log_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveExactDuplicateGroups(resolutions: ExactDuplicateResolution[]) : Promise<Result<ExactDuplicateResolutionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_exact_duplicate_groups", { resolutions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeImagesFromLibrary(ids: string[]) : Promise<Result<RemovedLifecycleMutationResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_images_from_library", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreRemovedImages(ids: string[]) : Promise<Result<RemovedLifecycleMutationResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_removed_images", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mutateCollectionMembership(input: CollectionMembershipMutationInput) : Promise<Result<CollectionMembershipMutationResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mutate_collection_membership", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateInvokeCollectionOwnership(collectionId: string, action: InvokeCollectionOwnershipAction) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_invoke_collection_ownership", { collectionId, action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async migrateLegacyCollections(input: LegacyCollectionMigrationInput) : Promise<Result<LegacyCollectionMigrationResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("migrate_legacy_collections", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAmbitCollectionScope(input: UpdateAmbitCollectionScopeInput) : Promise<Result<UpdateAmbitCollectionScopeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_ambit_collection_scope", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCollectionCustomThumbnail(collectionId: string, imageId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_collection_custom_thumbnail", { collectionId, imageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async backfillImageFileHashes(limit: number | null) : Promise<Result<FileHashBackfillResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backfill_image_file_hashes", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelImageFileHashBackfill() : Promise<void> {
    await TAURI_INVOKE("cancel_image_file_hash_backfill");
},
async refreshBoardsNative(boardMapping: Partial<{ [key in string]: string }>) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_boards_native", { boardMapping }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getImageCountForPathPrefix(path: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_image_count_for_path_prefix", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshPrivacyMaskIndex(maskedKeywords: string[]) : Promise<Result<PrivacyMaskRefreshResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_privacy_mask_index", { maskedKeywords }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshInvokeOwnerScope(input: InvokeOwnerScopeInput) : Promise<Result<InvokeOwnerScopeRefreshResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_invoke_owner_scope", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setInvokeBoardVerification(dbPath: string, ownerId: string, verified: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_invoke_board_verification", { dbPath, ownerId, verified }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async beginActiveInvokeScopeCacheBuild() : Promise<Result<InvokeScopeCacheBuildClaim, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("begin_active_invoke_scope_cache_build") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async abortActiveInvokeScopeCacheBuild(ticket: InvokeScopeCacheBuildTicket) : Promise<Result<FacetScopeCacheStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("abort_active_invoke_scope_cache_build", { ticket }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async commitActiveInvokeScopeCache(ticket: InvokeScopeCacheBuildTicket) : Promise<Result<FacetScopeCacheStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("commit_active_invoke_scope_cache", { ticket }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reconcileInvokeBoardSnapshot(input: InvokeBoardSnapshotInput) : Promise<Result<InvokeBoardSnapshotResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reconcile_invoke_board_snapshot", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async optimizeDatabase() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("optimize_database") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async schedulePurgeTransaction(transactionId: string, journalJson: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("schedule_purge_transaction", { transactionId, journalJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getParameterRanges(whereClause: string | null, paramsJson: string | null, collectionId: string | null, loraName: string | null) : Promise<Result<ParameterRanges, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_parameter_ranges", { whereClause, paramsJson, collectionId, loraName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async backfillParameterColumns() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backfill_parameter_columns") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rebuildFacetCache() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rebuild_facet_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rebuildFacetCacheIncremental(facetType: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rebuild_facet_cache_incremental", { facetType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rebuildFacetCacheIncrementalBatch(facetTypes: string[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rebuild_facet_cache_incremental_batch", { facetTypes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshFacetCacheForResources(touches: FacetResourceTouches) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_facet_cache_for_resources", { touches }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get distinct facet names that exist in the current filtered result set.
 * This is used for drill-down filtering - hiding facets that have no images
 * in the current filter context.
 * 
 * OPTIMIZATION: Uses a single UNION ALL query instead of 5 separate queries
 * to reduce database round-trips and allow SQLite to share table scans.
 */
async getValidFacetNames(whereClause: string, paramsJson: string, collectionId: string | null, loraName: string | null) : Promise<Result<ValidFacetNames, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_valid_facet_names", { whereClause, paramsJson, collectionId, loraName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markImagesCorrupt(ids: string[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_images_corrupt", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setImageSourceKind(imageIds: string[], sourceKindOverride: SourceKind | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_image_source_kind", { imageIds, sourceKindOverride }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async verifyLibraryIntegrity() : Promise<Result<IntegrityResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("verify_library_integrity") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start the single-pass metadata re-parsing job.
 * 
 * This command:
 * 1. Opens a dedicated database connection
 * 2. Streams all images using Keyset Pagination (WHERE id > last_id)
 * 3. Parses using Rayon
 * 4. Updates DB with Smart Diffing (skipping unchanged prompts/junctions)
 */
async startReparseJob(forceReparse: boolean, filterRoot: string | null, filterTool: string | null, refreshPhotoMetadata: boolean) : Promise<Result<ReparseJobResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_reparse_job", { forceReparse, filterRoot, filterTool, refreshPhotoMetadata }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel the currently running reparse job.
 */
async cancelReparseJob() : Promise<void> {
    await TAURI_INVOKE("cancel_reparse_job");
},
async getImagesNeedingReparse(limit: number | null) : Promise<Result<ImageToReparse[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_images_needing_reparse", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getReparseCount() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_reparse_count") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reparseMetadataBatch(images: ImageToReparse[]) : Promise<Result<ReparseBatchResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reparse_metadata_batch", { images }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetParserVersions() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_parser_versions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMetadataStats() : Promise<Result<MetadataStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_metadata_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBackups() : Promise<Result<BackupInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_backups") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async backupDatabase() : Promise<Result<BackupInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backup_database") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if we need to run an auto-backup (first run of the day).
 */
async checkAndRunAutobackup() : Promise<Result<BackupInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_and_run_autobackup") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async recordStartupDiagnostic(event: StartupDiagnosticEvent) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_startup_diagnostic", { event }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async recordStartupHeartbeat(launchId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_startup_heartbeat", { launchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async recordStartupLifecycle(launchId: string, stage: StartupLifecycleStage) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_startup_lifecycle", { launchId, stage }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStartupLaunch() : Promise<StartupLaunch> {
    return await TAURI_INVOKE("get_startup_launch");
},
async completeStartup() : Promise<void> {
    await TAURI_INVOKE("complete_startup");
},
async scanImage(path: string, thumbnailDir: string | null, skipThumbnail: boolean, extractWorkflow: boolean, defaultTool: string | null) : Promise<Result<ScanResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_image", { path, thumbnailDir, skipThumbnail, extractWorkflow, defaultTool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanImagesBulk(paths: string[], thumbnailDir: string | null, skipThumbnail: boolean, extractWorkflow: boolean, defaultTool: string | null, progressRunId: string | null) : Promise<Result<ScanResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_images_bulk", { paths, thumbnailDir, skipThumbnail, extractWorkflow, defaultTool, progressRunId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanImageWorkflow(path: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_image_workflow", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readImageMetadata(path: string, defaultTool: string | null) : Promise<Result<ImageMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_image_metadata", { path, defaultTool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFileSizesBulk(paths: string[]) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_sizes_bulk", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async probeFileMetadataBulk(paths: string[]) : Promise<Result<FileMetadataProbe[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("probe_file_metadata_bulk", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async verifyImagePaths(paths: string[]) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("verify_image_paths", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async auditInvokeaiFolder(path: string) : Promise<Result<FolderStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("audit_invokeai_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listInvokeaiImages(path: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_invokeai_images", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanDirectoryRecursive(path: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_directory_recursive", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openFile(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showInFolder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_in_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanDirectoryWithStats(path: string) : Promise<Result<FileEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_directory_with_stats", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanDirectorySince(path: string, since: number) : Promise<Result<FileEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_directory_since", { path, since }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discoverA1111Folders(rootPath: string) : Promise<Result<A1111DiscoveryResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_a1111_folders", { rootPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startThumbnailOptimizationJob(config: ThumbnailOptimizationConfig, ownerId: string) : Promise<Result<ThumbnailOptimizationResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_thumbnail_optimization_job", { config, ownerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async beginThumbnailRepairOperation(ownerId: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("begin_thumbnail_repair_operation", { ownerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async finishThumbnailRepairOperation(operationId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("finish_thumbnail_repair_operation", { operationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async repairThumbnailBatch(input: ThumbnailRepairBatchInput) : Promise<Result<ThumbnailRepairBatchResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("repair_thumbnail_batch", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelThumbnailOptimizationJob(operationId: number | null) : Promise<void> {
    await TAURI_INVOKE("cancel_thumbnail_optimization_job", { operationId });
},
async setThumbnailOptimizationThrottled(throttled: boolean) : Promise<void> {
    await TAURI_INVOKE("set_thumbnail_optimization_throttled", { throttled });
},
async getThumbnailOptimizationFailures(limit: number) : Promise<Result<ThumbnailOptimizationFailureList, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_thumbnail_optimization_failures", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async retryFailedThumbnailOptimizations() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_failed_thumbnail_optimizations") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startNativeFolderWatcher(paths: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_native_folder_watcher", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importA1111Cache(cachePath: string) : Promise<Result<ImportResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_a1111_cache", { cachePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveHashesOnline(skipHarvest: boolean) : Promise<Result<ResolutionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_hashes_online", { skipHarvest }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async inspectComfyuiMetadataChunks(chunks: Partial<{ [key in string]: string }>) : Promise<Result<ComfyParserDiagnosticsReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("inspect_comfyui_metadata_chunks", { chunks }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async inspectComfyuiWorkflowGraph(chunks: Partial<{ [key in string]: string }>) : Promise<Result<ComfyWorkflowGraphReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("inspect_comfyui_workflow_graph", { chunks }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearModelCache() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_model_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelModelResolution() : Promise<void> {
    await TAURI_INVOKE("cancel_model_resolution");
},
async cancelModelDiscovery() : Promise<void> {
    await TAURI_INVOKE("cancel_model_discovery");
},
async scanModelThumbnails(paths: string[]) : Promise<Result<ThumbnailScanResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_model_thumbnails", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async purgeResourceFolderAssets(path: string, remainingPaths: string[]) : Promise<Result<ResourcePurgeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("purge_resource_folder_assets", { path, remainingPaths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setModelThumbnail(modelHash: string, modelName: string | null, imagePath: string, resourceType: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_model_thumbnail", { modelHash, modelName, imagePath, resourceType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unsetModelThumbnail(modelHash: string, modelName: string | null, resourceType: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unset_model_thumbnail", { modelHash, modelName, resourceType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearAllThumbnails(modelHash: string, modelName: string | null, resourceType: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_all_thumbnails", { modelHash, modelName, resourceType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setResourceThumbnailSensitivity(modelHash: string, modelName: string | null, sensitivity: boolean | null, resourceType: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_resource_thumbnail_sensitivity", { modelHash, modelName, sensitivity, resourceType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importVideoAsset(path: string, operationId: string) : Promise<Result<VideoImportOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_video_asset", { path, operationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshVideoMetadata(filterRoot: string | null, forceReparse: boolean) : Promise<Result<ReparseJobResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_video_metadata", { filterRoot, forceReparse }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelVideoImport(operationId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_video_import", { operationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async storeVideoPoster(assetId: string, webpBase64: string) : Promise<Result<VideoPosterResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("store_video_poster", { assetId, webpBase64 }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async prepareVideoPlayback(assetId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prepare_video_playback", { assetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportAssetOriginal(assetId: string, destinationDirectory: string) : Promise<Result<ExportOriginalResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_asset_original", { assetId, destinationDirectory }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveToTrash(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_to_trash", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteRemovedImagesFromDisk(ids: string[]) : Promise<Result<DeleteRemovedImagesResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_removed_images_from_disk", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteThumbnail(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_thumbnail", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async registerLibraryPath(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_library_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInvokeDbSnapshot(rootPath: string) : Promise<Result<InvokeDbSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_invoke_db_snapshot", { rootPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
folderChangeEvent: FolderChangeEvent,
thumbnailOptimizationComplete: ThumbnailOptimizationComplete,
thumbnailOptimizationProgress: ThumbnailOptimizationProgress
}>({
folderChangeEvent: "folder-change-event",
thumbnailOptimizationComplete: "thumbnail-optimization-complete",
thumbnailOptimizationProgress: "thumbnail-optimization-progress"
})

/** user-defined constants **/



/** user-defined types **/

export type A1111DiscoveryCandidate = { path: string; name: string; imageCount: number; inferredType: string; isPriority: boolean; variant: string }
export type A1111DiscoveryResult = { detectedVariant: string; candidates: A1111DiscoveryCandidate[]; logs: string[]; warnings: string[] }
export type AmbitCollectionScopeMode = "global" | "all" | "owner"
export type BackupInfo = { name: string; path: string; createdAt: string; sizeBytes: number }
export type CaptureTimeMetadata = { local: string; offset: string | null; subsecond: string | null }
export type CollectionMembershipMutationInput = { operation: CollectionMembershipOperation; imageIds: string[]; sourceCollectionId: string | null; targetCollectionId: string | null }
export type CollectionMembershipMutationResult = { affectedIds: string[]; sourceCollectionId: string | null; targetCollectionId: string | null }
export type CollectionMembershipOperation = "add" | "remove" | "move"
export type ComfyMetadataPreview = { tool: string; model: string; seed: number | null; steps: number; cfg: number; sampler: string; positivePrompt: string; negativePrompt: string; loras: string[]; controlNets: string[]; ipAdapters: string[]; embeddings: string[]; hypernetworks: string[]; generationType: string; hasWorkflowHint: boolean; hasWorkflowJson: boolean }
export type ComfyParserDiagnosticsReport = { appVersion: string; parserVersion: number; chunkKeys: string[]; hasPromptChunk: boolean; hasWorkflowChunk: boolean; graphNodeCount: number; selectedOutputCandidateCount: number; uniqueOutputRootSamplerCount: number; outputAmbiguous: boolean; traversalIssues: ComfyTraversalIssueReport[]; traversalIssuesTruncated: boolean; attemptedLayers: string[]; fieldSources: Partial<{ [key in string]: string }>; fieldSourceNodeIds?: Partial<{ [key in string]: string[] }>; resourceSources?: ComfyResourceSourceReport[]; metadata: ComfyMetadataPreview }
export type ComfyResourceSourceReport = { field: string; value: string; layer: string | null; nodeIds: string[] }
export type ComfyTraversalIssueReport = { field: string; nodeId: string; nodeType: string; inputName: string | null; reason: string }
export type ComfyWorkflowDisplayEdge = { sourceNodeId: string; sourceOutputSlot: number | null; targetNodeId: string; targetInputName: string; targetInputSlot: number | null }
export type ComfyWorkflowDisplayNode = { id: string; nodeType: string; title: string; inputs: Partial<{ [key in string]: string }>; subgraphPath: string[] }
export type ComfyWorkflowGraphReport = { source: string; nodeCount: number; nodes: ComfyWorkflowDisplayNode[]; edges: ComfyWorkflowDisplayEdge[]; selectedOutputNodeIds: string[]; rootSamplerNodeIds: string[]; selectedBranchNodeIds: string[]; outputAmbiguous: boolean }
export type DbDiagnostics = { dbPath: string; activeDbPath: string; localDbPath: string; roamingDbPath: string; appLogDir: string; appLogPath: string; isUsingRoamingFallback: boolean; imageCount: number; deletedCount: number; modelCount: number; cacheCount: number; toolNullCount: number }
export type DeleteRemovedImagesResult = { clearedIds: string[]; trashedIds: string[]; alreadyMissingIds: string[]; failedIds: string[]; cleanupPendingIds: string[]; thumbnailWarningIds: string[]; notFoundIds: string[] }
export type ExactDuplicateKeeperState = { id: string; isFavorite: boolean; isPinned: boolean; userMasked: boolean | null }
export type ExactDuplicateResolution = { keepId: string; removeIds: string[] }
export type ExactDuplicateResolutionResult = { resolvedGroups: number; removedIds: string[]; keepers: ExactDuplicateKeeperState[] }
export type ExportOriginalResult = { assetId: string; outputPath: string; bytesCopied: number }
export type FacetResourceTouches = { checkpoints: string[]; loras: string[]; embeddings: string[]; hypernetworks: string[]; controlNets: string[]; ipAdapters: string[]; tools: string[] }
export type FacetScopeCacheState = "missing" | "dirty" | "building" | "ready"
export type FacetScopeCacheStatus = { state: FacetScopeCacheState; generation: number; builtGeneration: number | null; facetCount: number; collectionCount: number }
export type FileEntry = { path: string; modified: number; size: number; mediaType: MediaCandidateKind }
export type FileHashBackfillResult = { scanned: number; updated: number; missing: number; errors: number; remaining: number; wasCancelled: boolean }
export type FileMetadataProbe = { status: "present"; size: number; isFile: boolean } | { status: "missing" } | { status: "error"; message: string }
export type FolderChange = { kind: FolderChangeKind; paths: string[] }
export type FolderChangeEvent = FolderChange[]
export type FolderChangeKind = "create" | "modify" | "rename" | "remove"
export type FolderStats = { totalFiles: number; imageFiles: number; videoFiles: number; thumbnailFiles: number; otherFiles: number; directoryChecked: string; subfolders: Partial<{ [key in string]: number }> }
export type ImageMetadata = { tool: string; model: string; rawParameters?: string | null; steps: number; cfg: number; seed?: number | null; sampler: string; positivePrompt: string; negativePrompt: string; loras: string[]; controlNets: string[]; ipAdapters: string[]; embeddings: string[]; hypernetworks: string[]; variationId?: string | null; isIntermediate?: boolean; isGrid?: boolean; workflowJson?: string | null; vae?: string | null; clipSkip?: number | null; denoisingStrength?: number | null; hiresUpscale?: number | null; hiresSteps?: number | null; hiresUpscaler?: string | null; modelHash?: string | null; generationType: string; isFavorite?: boolean; hasWorkflowHint?: boolean }
export type ImagePathIdentityMove = { oldId: string; newId: string; thumbnailPath: string | null; thumbnailSource: string | null }
export type ImagePathIdentityMoveResult = { moved: number; skippedTargetExists: number; skippedSourceMissing: number }
export type ImageRecord = { id: string; path: string; width: number; height: number; fileSize: number; fileHash: string | null; timestamp: number; metadataJson: string; thumbnailPath: string; 
/**
 * Base64 encoded 32px WebP micro-thumbnail for instant previews
 */
microThumbnail: string | null; 
/**
 * Source of the thumbnail: 'ambit', 'invokeai', etc.
 */
thumbnailSource: string | null; thumbnailVersion: number; detectedSourceKind: SourceKind; sourceKindOverride: SourceKind | null; photoMetadata: PhotoMetadata | null; photoMetadataError: string | null; captureWallTimeMs: number | null; isFavorite: boolean; isPinned: boolean; isDeleted: boolean; isMissing: boolean; isCorrupt: boolean; userMasked: boolean | null; groupId: string | null; boardId: string | null; notes: string | null; originalMetadataJson: string | null; originalStateJson: string | null; invokeImageName: string | null; invokeImageCategory: string | null; invokeImageOrigin: string | null; invokeOwnerId: string | null }
export type ImageToReparse = { id: string; tool: string; originalMetadataJson: string }
export type ImportResult = { added: number; totalFound: number; message: string }
export type IntegrityResult = { missing: number; recovered: number; broken_thumbs: number }
export type InvokeBoardSnapshotBoard = { id: string; name: string; createdAt: number; ownerId: string | null }
export type InvokeBoardSnapshotInput = { dbPath: string; mode: InvokeOwnerScopeMode; ownerId: string | null; boards: InvokeBoardSnapshotBoard[]; memberships: InvokeBoardSnapshotMembership[]; reconcileMemberships: boolean; deleteMissingCollections: boolean }
export type InvokeBoardSnapshotMembership = { imageName: string; boardId: string }
export type InvokeBoardSnapshotResult = { collectionsUpdated: number; collectionsDeleted: number; imagesUpdated: number; membershipsDeleted: number; membershipsInserted: number }
export type InvokeCollectionOwnershipAction = "suppress" | "restore" | "reset"
export type InvokeDbSnapshot = { dbPath: string; files: InvokeDbSnapshotFile[] }
export type InvokeDbSnapshotFile = { path: string; exists: boolean; size: number; modifiedMs: number | null }
export type InvokeImageOwnerInventoryInput = { dbPath: string; images: InvokeImageOwnerInventoryItem[] }
export type InvokeImageOwnerInventoryItem = { id: string; invokeOwnerId: string | null }
export type InvokeImageReferenceInput = { role: InvokeImageReferenceRole; targetInvokeImageName: string }
export type InvokeImageReferenceReplaceResult = { sourcesReplaced: number; referencesWritten: number; skippedMissingSources: number }
export type InvokeImageReferenceRole = "init_image" | "controlnet_image" | "controlnet_processed_image" | "ip_adapter_image" | "t2i_adapter_image" | "t2i_adapter_processed_image"
export type InvokeImageReferenceSet = { sourceImageId: string; references: InvokeImageReferenceInput[] }
export type InvokeImageSourceReconcileResult = { activeUpdated: number; removedUpdated: number }
export type InvokeImageSourceUpdate = { id: string; invokeImageName: string; invokeImageCategory: string | null; invokeImageOrigin: string | null; invokeOwnerId: string | null }
export type InvokeOwnerScopeInput = { dbPath: string; imagesRoot: string; mode: InvokeOwnerScopeMode; ownerId: string | null; forceRefresh: boolean }
export type InvokeOwnerScopeMode = "legacy" | "unselected" | "owner" | "all"
export type InvokeOwnerScopeRefreshResult = { changed: boolean; activeUpdated: number; removedUpdated: number; cacheStatus: FacetScopeCacheStatus; cacheRepair: InvokeScopeCacheRepairPlan }
export type InvokeScopeCacheAction = "restored" | "selective" | "full"
export type InvokeScopeCacheBuildClaim = { scopeKey: string; generation: number; cacheStatus: FacetScopeCacheStatus; cacheRepair: InvokeScopeCacheRepairPlan }
export type InvokeScopeCacheBuildTicket = { scopeKey: string; generation: number }
export type InvokeScopeCacheRepairPlan = { action: InvokeScopeCacheAction; resources: FacetResourceTouches; facetTypes: string[]; collectionsDirty: boolean }
export type LegacyCollectionMigrationInput = { importKey: string; collections: LegacyCollectionMigrationItem[] }
export type LegacyCollectionMigrationItem = { id: string; name: string; color: string | null; isArchived: boolean; isPinned: boolean; createdAt: number; updatedAt: number | null; filterState: string | null; manualExclusions: string | null; customThumbnail: string | null; imageIds: string[] }
export type LegacyCollectionMigrationResult = { alreadyApplied: boolean; collectionsUpserted: number; membershipsInserted: number }
export type MediaCandidateKind = "image" | "video"
export type MetadataEvidenceSource = "user_override" | "trusted_sidecar" | "embedded" | "workflow_default" | "unknown"
export type MetadataStats = { total: number; with_raw: number; with_pv: number; v0: number; v1: number }
export type NumericRange = { min: number; max: number }
export type ParameterRanges = { steps: NumericRange | null; cfg: NumericRange | null; denoisingStrength: NumericRange | null; samplers: string[]; generationTypes: string[]; controlNets: string[]; ipAdapters: string[]; guidanceSubtypes: Partial<{ [key in string]: string }> }
export type PhotoMetadata = { capturedAt: CaptureTimeMetadata | null; captureTimeRaw: string | null; cameraMake: string | null; cameraModel: string | null; lensMake: string | null; lensModel: string | null; focalLengthMm: number | null; focalLength35Mm: number | null; apertureFNumber: number | null; exposureTimeSeconds: number | null; iso: number | null; orientation: number | null; artist: string | null; copyright: string | null; gpsLatitude: number | null; gpsLongitude: number | null }
export type PrivacyMaskRefreshResult = { changed: boolean; updated: number }
export type RemovedLifecycleMutationResult = { affectedIds: string[]; notFoundIds: string[]; membershipWarningIds: string[]; touchedResources: FacetResourceTouches }
export type ReparseBatchResult = { processed: number; updated: number; errors: number }
/**
 * Result of a reparse job.
 */
export type ReparseJobResult = { processed: number; updated: number; errors: number; wasCancelled: boolean }
export type ResolutionResult = { resolvedCount: number; harvestedCount: number; failedCount: number; namedFallbackCount: number; unknownCount: number }
export type ResourcePurgeResult = { removedModels: number; preservedModels: number; removedScannedFiles: number; refreshedFacets: number; resources: FacetResourceTouches }
export type ScanResult = { width: number; height: number; size: number; modified: number; thumbnail: string; 
/**
 * Base64 encoded 32px WebP micro-thumbnail for instant previews
 */
microThumbnail: string | null; 
/**
 * Source of the thumbnail: 'ambit', 'invokeai', etc.
 */
thumbnailSource: string | null; chunks: Partial<{ [key in string]: string }>; metadata: ImageMetadata | null; 
/**
 * Error message if scan failed or resulted in a partial result
 */
error: string | null; thumbnailVersion: number; detectedSourceKind: SourceKind; photoMetadata: PhotoMetadata | null; photoMetadataError: string | null; captureWallTimeMs: number | null }
export type SimilarImageHit = { id: string; distance: number }
export type SourceKind = "generated" | "photograph" | "other"
export type StartupCacheAction = "restored" | "selective" | "full"
export type StartupDatabaseRole = "ambit" | "invoke-source" | "mixed"
export type StartupDiagnosticEvent = { launchId: string; phase: StartupPhase; status: StartupPhaseStatus; elapsedMs: number; durationMs: number | null; cacheAction: StartupCacheAction | null; databaseRole?: StartupDatabaseRole | null; attempt?: number | null; failureKind?: StartupFailureKind | null; repairDecision?: StartupRepairDecision | null; repairStage?: StartupRepairStage | null; repairReport?: StartupRepairReport | null }
export type StartupFailureKind = "script-load" | "uncaught-error" | "unhandled-rejection" | "render-error" | "database-busy" | "database-locked" | "other"
export type StartupLaunch = { launchId: string; processElapsedMs: number }
export type StartupLifecycleStage = "close-requested" | "settings-drain-started" | "settings-drain-completed" | "settings-drain-failed" | "settings-flush-started" | "settings-flush-completed" | "settings-flush-failed" | "exit-invoked" | "exit-failed"
export type StartupPhase = "frontend-entry" | "react-mount" | "startup-failure" | "renderer-stall" | "maintenance-counts" | "invoke-catch-up" | "database" | "database-schema" | "database-optimization" | "database-pragmas" | "database-indexes" | "owner-discovery" | "owner-source-open" | "owner-source-schema" | "owner-source-images" | "owner-source-boards" | "owner-fingerprint" | "owner-source-repair" | "owner-board-read" | "owner-board-write" | "owner-visibility" | "owner-board-verification" | "owner-preparation" | "owner-cache" | "facets" | "collections" | "collection-rows" | "collection-counts" | "privacy" | "first-page" | "gallery-rows" | "gallery-count" | "gallery-global-count" | "statistics-media" | "statistics-steps" | "statistics-models" | "facet-counts" | "splash" | "ready" | "thumbnail-maintenance" | "metadata-maintenance" | "owner-repair-decision" | "owner-repair-stage" | "owner-repair-report"
export type StartupPhaseStatus = "started" | "completed" | "failed" | "cancelled"
export type StartupRepairCountComparison = "unavailable" | "decreased" | "equal" | "increased"
export type StartupRepairCounters = { identityRows: number; factRows: number; pathsChecked: number; inventorySubmitted: number; inventoryApplied: number; factsSubmitted: number; factsApplied: number; referenceSetsSubmitted: number; referenceSourcesReplaced: number }
export type StartupRepairDecision = { decision: StartupRepairDecisionKind; scope: StartupRepairScope; forcedRefresh: boolean; snapshot: StartupRepairSnapshot; savedFingerprint: StartupRepairFingerprint; currentFingerprint: StartupRepairFingerprint; countComparison: StartupRepairCountComparison; timestampComparison: StartupRepairTimestampComparison; fingerprintCurrent: boolean | null }
export type StartupRepairDecisionKind = "unchanged" | "incremental-catch-up" | "full-repair" | "no-admitted-scope"
export type StartupRepairFingerprint = "unavailable" | "supported" | "unsupported"
export type StartupRepairMetric = { operation: StartupRepairMetricOperation; calls: number; totalMs: number; maxMs: number }
export type StartupRepairMetricOperation = "setup" | "identity-read" | "identity-paths" | "identity-matching" | "legacy-paths" | "inventory" | "fact-read" | "fact-paths" | "fact-extraction" | "fact-write" | "reference-write" | "batch-yield" | "filesystem-enumeration" | "inventory-build"
export type StartupRepairReport = { status: StartupRepairStatus; durationMs: number; unattributedMs: number; metrics: StartupRepairMetric[]; counters: StartupRepairCounters }
export type StartupRepairScope = "none" | "legacy" | "all" | "owner"
export type StartupRepairSnapshot = "missing" | "compatible" | "incompatible"
export type StartupRepairStage = "setup" | "identity" | "legacy-paths" | "inventory" | "facts"
export type StartupRepairStatus = "completed" | "failed" | "cancelled"
export type StartupRepairTimestampComparison = "unavailable" | "saved-absent" | "current-absent" | "decreased" | "equal" | "increased"
export type ThumbnailOptimizationComplete = ThumbnailOptimizationResult
export type ThumbnailOptimizationConfig = { thumbnailDir: string; includeUpgradeable: boolean; profile: ThumbnailOptimizationProfile; sourceRoots?: string[] }
export type ThumbnailOptimizationFailure = { id: string; path: string; thumbnailPath: string | null; failureCount: number; lastError: string | null; lastAttemptAt: number | null }
export type ThumbnailOptimizationFailureList = { failures: ThumbnailOptimizationFailure[] }
export type ThumbnailOptimizationPhase = "discovering" | "processing" | "persisting" | "throttled" | "complete"
export type ThumbnailOptimizationProfile = "quiet" | "balanced" | "fast"
export type ThumbnailOptimizationProgress = { checked: number; total: number | null; optimized: number; reused: number; missing: number; failed: number; skipped: number; imagesPerSecond: number; batchMs: number; dbMs: number; encodeMs: number; candidateFetchMs: number; profile: ThumbnailOptimizationProfile; phase: ThumbnailOptimizationPhase; message: string; isThrottled: boolean }
export type ThumbnailOptimizationResult = { checked: number; optimized: number; reused: number; missing: number; failed: number; skipped: number; wasCancelled: boolean; durationMs: number }
export type ThumbnailRepairBatchInput = { operationId: number; ids: string[]; thumbnailDir: string; sourceRoots?: string[]; force: boolean; respectBackoff: boolean }
export type ThumbnailRepairBatchResult = { requested: number; checked: number; optimized: number; reused: number; missing: number; failed: number; skipped: number; wasCancelled: boolean; durationMs: number; candidateFetchMs: number; dbMs: number; encodeMs: number; updates: ThumbnailRepairUpdate[] }
export type ThumbnailRepairUpdate = { id: string; thumbnailPath: string }
export type ThumbnailScanResult = { found: number; updated: number; cachedFiles: number; newOrChangedFiles: number; registeredModels: number; resources: FacetResourceTouches }
export type UpdateAmbitCollectionScopeInput = { collectionId: string; mode: AmbitCollectionScopeMode; dbPath: string | null; ownerId: string | null }
export type UpdateAmbitCollectionScopeResult = { collectionId: string; invokeSourceId: string | null; invokeOwnerId: string | null }
/**
 * Valid facet names result - used for drill-down filtering
 */
export type ValidFacetNames = { checkpoints: string[]; loras: string[]; embeddings: string[]; hypernetworks: string[]; tools: string[]; controlNets: string[]; ipAdapters: string[] }
export type VideoAssetRecord = { id: string; path: string; width: number; height: number; fileSize: number; timestamp: number; mediaContainer: string | null; mediaMimeType: string | null; durationMs: number; videoCodec: string; videoProfile: string | null; audioPresent: boolean; audioCodec: string | null; frameRateNum: number | null; frameRateDen: number | null; rotationDegrees: number; metadata: VideoGenerationMetadata; originalMetadataJson: string }
export type VideoGenerationMetadata = { tool: string; model: string; seed: number | null; steps: number; cfg: number; sampler: string; positivePrompt: string; negativePrompt: string; loras: string[]; controlNets: string[]; ipAdapters: string[]; generationType: string; generationMode: VideoGenerationMode; workflowJson: string | null; fieldSources: Partial<{ [key in string]: MetadataEvidenceSource }>; conflicts: VideoMetadataConflict[]; diagnostics: VideoMetadataDiagnostic[]; parserVersion: number }
export type VideoGenerationMode = "text_to_video" | "image_to_video" | "first_last_frame_to_video" | "video_editing" | "audio_lip_sync" | "guided_video" | "unknown"
export type VideoImportOutcome = { status: string; asset: VideoAssetRecord | null; reason: string | null }
export type VideoMetadataConflict = { field: string; selectedValue: string; ignoredValue: string; ignoredSource: MetadataEvidenceSource }
export type VideoMetadataDiagnostic = { code: string; message: string }
export type VideoPosterResult = { assetId: string; thumbnailPath: string; thumbnailSource: string }
export type VisualBackfillResult = { updated: number; remaining: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
